language: node_js
node_js:
- '10'
cache: yarn
install: yarn install --frozen-lockfile
stages:
- name: test
- name: deploy
jobs:
  include:
  - stage: test
    script: yarn test
  - stage: deploy
    script:
    - yarn build:dev
    before_deploy:
    - export RELEASE_TAG=$(jq .version package.json | tr -d \" | cut -d . -f "1 2")
    deploy:
    - provider: s3
      bucket: auth-dev.endpass.com
      region: us-east-1
      skip_cleanup: true
      local_dir: dist/app
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master$|^v[0-9]+\\.[0-9]+$"
    - provider: s3
      bucket: auth-dev.endpass.com
      region: us-east-1
      skip_cleanup: true
      local_dir: dist/app
      upload-dir: v$RELEASE_TAG
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master$|^v[0-9]+\\.[0-9]+$"
notifications:
  slack:
    secure: bFhnj+Bs2xUVA7zznhvsJGGsWJhKA/hGfIoHFrvdD7uDhYmaW08+iFItXIfx7weO/BhiB4Zim7usFFsbsKPnqPC1OpBUW5TRE4kjg29AFdMXmtsPpqMi4tAJs5kPJKBg7Z5TSiFtM8qw9LrSAyuy09DTzQd2e1PBs7/S92eUceeF1gupqts9/ZXpBu5uDlwCirVyV8DMFrZDMkfmxxyHFSnuYU+cv8bKbEp2Bks5ByGvkUYe8tRAp5Fge6TUv/uBnwEpo5VLjdEVP/BKLyXPWoHvxVPQdZYUnEe7LNuDrgNEJuuLc02vJP0Xrd0d38hd9qtk1rD/f7SoZj6KYR11jdrI6lXfEMclda73rKEscFCBVrOD73AeotcZ79eXFcBqXgAqWtH4xCiW+y46VDsHClVdKh40kaKT4+Letw24kGtXiHY5/3Pqd5cHDa+3SLd6LyJzTTkDbXToHRqSd9WEPV7JBO2i01rTGFB/iufpcA7NkyYF2Gbx5S4YLSgtZMzRY7YnzAjSTpA9KEDnDrkmVj29TEhtrMHSis9DcVEG7DqEkMC61aUS+zt+we+RyFLUQsvP/EyN++xIuoTBrk4OH0kka3Gltr3D/hhfdfXGRqF4q3sdNzOit8FjmG/sQ/k85mi49Qm2p7hzkDZqBeZD5fGPt7xs20jeU9hanMHnlpE=
